{
 "title": "Router Main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of Channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "router_channels_total" }
   ]
  },
  {
   "title": "Collateral By Channel (ETH)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "router_channels_collateral{assetId=\"0x0000000000000000000000000000000000000000\"}",
     "legendFormat": "{{channelAddress}}"
    }
   ]
  },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Transfers By Channel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "router_active_transfers", "legendFormat": "{{channelAddress}}" }
   ]
  },
  {
   "title": "Forwarded Transfers",
   "type": "graph",
   "description": "Total, successful, and failed forwarded payment attempts by router.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(router_failed) / sum(router_forwarded_payment_attempts)",
     "legendFormat": "Failure Rate"
    },
    {
     "expr": "sum(router_successful_forwarded_payments) / sum(router_forwarded_payment_attempts)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Transfer Forward Timings (Router to Receiver)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "router_sent_payments_time" }
   ]
  }
 ]
}