{
 "title": "Router Main",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Router Onchain Liquidity",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "router_onchain_liquidity" }
   ]
  },
  {
   "title": "Number of Channels",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "targets": [
    { "expr": "router_channels" }
   ]
  },
  {
   "title": "Router Offchain Liquidity",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "router_offchain_liquidity" }
   ]
  },
  {
   "title": "Successful vs Failed Forwarded Transfers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "router_transfer_successful",
     "legendFormat": "Successful: chain {{chainId}} - {{assetId}}"
    },
    {
     "expr": "router_transfer_failed",
     "legendFormat": "Failed: chain {{chainId}} - {{assetId}}"
    }
   ]
  },
  {
   "title": "Onchain Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "router_transaction_success",
     "legendFormat": "Successful: chain {{chainId}} - {{reason}}"
    },
    {
     "expr": "router_transaction_failed",
     "legendFormat": "Failed: chain {{chainId}} - {{reason}}"
    }
   ]
  },
  {
   "title": "24h Volume",
   "type": "stat",
   "description": "Volume of router over the last 24 hours",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(router_transfer_volume[24h])",
     "legendFormat": "chain {{chainId}} - {{assetId}}"
    }
   ]
  },
  {
   "title": "Weekly Volume",
   "type": "stat",
   "description": "Router volume over the last week",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(router_transfer_volume[7d])",
     "legendFormat": "chain {{chainId}} - {{assetId}}"
    }
   ]
  },
  {
   "title": "Gas Consumed",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (chainId) (router_gas_consumed)"
    }
   ]
  }
 ]
}