{
 "title": "Router Main 2",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Weekly Volume",
   "type": "graph",
   "description": "Router volume over the last week",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(router_transfer_volume[7d]))",
     "legendFormat": "chain {{chainId}} - {{assetId}}"
    }
   ]
  },
  {
   "title": "24h Volume",
   "type": "graph",
   "description": "Volume of router over the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(router_transfer_volume[24h]))",
     "legendFormat": "chain {{chainId}} - {{assetId}}"
    }
   ]
  },
  {
   "title": "Transfers per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(router_transfer_attempt[1h]))"
    }
   ]
  },
  {
   "title": "Total Available Liquidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(router_onchain_liquidity)+sum(router_offchain_liquidity)"
    }
   ]
  },
  {
   "title": "Transfer Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(router_transfer_failed/router_transfer_attempt)"
    }
   ]
  },
  {
   "title": "Onchain Transactions Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - min(router_transaction_success/router_transaction_attempt)",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Transfer Sizes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "router_transfer_size" }
   ]
  },
  {
   "title": "Number of Channels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(router_channels[10y])" }
   ]
  },
  {
   "title": "Gas Consumed",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum by (chainId) (router_gas_consumed)"
    }
   ]
  },
  {
   "title": "Router Onchain Liquidity",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "router_onchain_liquidity" }
   ]
  }
 ]
}