@aliceUrl = http://localhost:8003
@bobUrl = http://localhost:8004
@carolUrl = http://localhost:8005
@daveUrl = http://localhost:8006
@rogerUrl = http://localhost:8007
@aliceBobChannel = 0xD7b60870a3a0D52A2b9F7daBe5DCaB8EDC5bCD4e
@carolRogerChannel = 0xEd985dC74648f968F9B42Ef2CCF2ed98777f4C3A
@daveRogerChannel = 0x05b2FFe2814240aa788FcD38Fe0DB29354E6d789
@adminToken = cxt1234
@alicePublicIdentifier = indra8WxfqTu8EC2FLM6g4y6TgbSrx4EPP9jeDFQk3VBsBM7Jv8NakR
@bobPublicIdentifier = indra5ArRsL26avPNyfvJd2qMAppsEVeJv11n31ex542T9gCd5B1cP3
@carolPublicIdentifier = indra8ZaxNSdUM83kLXJSsmj5jrcq17CpZUwBirmboaNPtQMEXjVNrL
@davePublicIdentifier = indra7mAydt3S3dDPWJMYSHZPdRo16Pru145qTNQYFoS8TrpXWW8HAj
@rogerPublicIdentifier = indra8Uz1BdpA9hV5uTm6QUv5jj1PsUyCH8m8ciA94voCzsxVmrBRor
@chainId = 1337

##############
### GET CONFIG
GET {{carolUrl}}/config

##############
### GET CHANNELS
GET {{aliceUrl}}/{{alicePublicIdentifier}}/channel

##############
### GET CHANNEL
GET {{aliceUrl}}/{{alicePublicIdentifier}}/channel/{{aliceBobChannel}}

##############
### GET CHANNEL BY PARTICIPANTS
GET {{carolUrl}}/{{carolPublicIdentifier}}/channels/counterparty/{{rogerPublicIdentifier}}/chain-id/{{chainId}}

##############
### CLEAR STORE
POST {{aliceUrl}}/clear-store
Content-Type: application/json

{
  "adminToken": "{{adminToken}}"
}

##############
### CREATE NODE
POST {{carolUrl}}/node
Content-Type: application/json

{
  "index": 0
}
