@aliceUrl = http://localhost:8001
@bobUrl = http://localhost:8002
@adminToken = cxt1234

##############
### GET CONFIG
### Alice
GET {{aliceUrl}}/config

### Bob
GET {{bobUrl}}/config

##############
### CLEAR STORE
### Alice
POST {{aliceUrl}}/clear-store
Content-Type: application/json

{
  "adminToken": "{{adminToken}}"
}

### Bob
POST {{bobUrl}}/clear-store
Content-Type: application/json

{
  "adminToken": "{{adminToken}}"
}