@aliceUrl = http://localhost:8003
@bobUrl = http://localhost:8004
@rogerUrl = http://localhost:8000
@aliceBobChannel = 0x71804AfF6Ab73CC4507bA0E0F500e52349C0f2de
@aliceRogerChannel = 0x228143668de2eD7d4386EB81517c08fb3aA07538
@bobRogerChannel = 0x927c6026c3b8130251f528ef0CAFfab4fae57402
@adminToken = cxt1234
@alicePublicIdentifier = indra8WxfqTu8EC2FLM6g4y6TgbSrx4EPP9jeDFQk3VBsBM7Jv8NakR
@bobPublicIdentifier = indra5ArRsL26avPNyfvJd2qMAppsEVeJv11n31ex542T9gCd5B1cP3
@rogerPublicIdentifier = indra8AXWmo3dFpK1drnjeWPyi9KTy9Fy3SkCydWx8waQrxhnW4KPmR
@chainId = 1337

##############
### GET CONFIG
GET {{aliceUrl}}/config

##############
### GET CHANNELS
GET {{aliceUrl}}/channel

##############
### GET CHANNEL
GET {{aliceUrl}}/channel/{{aliceBobChannel}}

##############
### GET CHANNEL BY PARTICIPANTS
GET {{aliceUrl}}/channel/{{alicePublicIdentifier}}/{{bobPublicIdentifier}}/{{chainId}}

##############
### CLEAR STORE
POST {{aliceUrl}}/clear-store
Content-Type: application/json

{
  "adminToken": "{{adminToken}}"
}