@aliceUrl = http://localhost:8003
@bobUrl = http://localhost:8004
@carolUrl = http://localhost:8005
@daveUrl = http://localhost:8006
@rogerUrl = http://localhost:8007
@aliceBobChannel = 0xD7b60870a3a0D52A2b9F7daBe5DCaB8EDC5bCD4e
@carolRogerChannel = 0x66920C67620b492C3FF7f904af6DC3a8B58D7C9C
@daveRogerChannel = 0x7E513218D56ef4465208d587e9eff56e9035cd02
@adminToken = cxt1234
@alicePublicIdentifier = vector8WxfqTu8EC2FLM6g4y6TgbSrx4EPP9jeDFQk3VBsBM7Jv8NakR
@bobPublicIdentifier = vector5ArRsL26avPNyfvJd2qMAppsEVeJv11n31ex542T9gCd5B1cP3
@carolPublicIdentifier = vector8ZaxNSdUM83kLXJSsmj5jrcq17CpZUwBirmboaNPtQMEXjVNrL
@davePublicIdentifier = vector7mAydt3S3dDPWJMYSHZPdRo16Pru145qTNQYFoS8TrpXWW8HAj
@rogerPublicIdentifier = vector8Uz1BdpA9hV5uTm6QUv5jj1PsUyCH8m8ciA94voCzsxVmrBRor
@chainId = 1337

@nodeUrl = {{carolUrl}}
@nodePublicIdentifier = {{carolPublicIdentifier}}
@counterpartyPublicIdentifier = {{rogerPublicIdentifier}}

##############
### Setup Channel
POST {{nodeUrl}}/setup
Content-Type: application/json

{
  "counterpartyIdentifier": "{{counterpartyPublicIdentifier}}",
  "publicIdentifier": "{{nodePublicIdentifier}}",
  "chainId": "{{chainId}}",
  "timeout": "100000"
}