@aliceUrl = http://localhost:8003
@bobUrl = http://localhost:8004
@carolUrl = http://localhost:8005
@daveUrl = http://localhost:8006
@rogerUrl = http://localhost:8007
@aliceBobChannel = 0xD7b60870a3a0D52A2b9F7daBe5DCaB8EDC5bCD4e
@carolRogerChannel = 0xEd985dC74648f968F9B42Ef2CCF2ed98777f4C3A
@daveRogerChannel = 0x05b2FFe2814240aa788FcD38Fe0DB29354E6d789
@adminToken = cxt1234
@alicePublicIdentifier = vector8WxfqTu8EC2FLM6g4y6TgbSrx4EPP9jeDFQk3VBsBM7Jv8NakR
@bobPublicIdentifier = vector5ArRsL26avPNyfvJd2qMAppsEVeJv11n31ex542T9gCd5B1cP3
@carolPublicIdentifier = vector8ZaxNSdUM83kLXJSsmj5jrcq17CpZUwBirmboaNPtQMEXjVNrL
@davePublicIdentifier = vector7mAydt3S3dDPWJMYSHZPdRo16Pru145qTNQYFoS8TrpXWW8HAj
@rogerPublicIdentifier = vector8Uz1BdpA9hV5uTm6QUv5jj1PsUyCH8m8ciA94voCzsxVmrBRor
@chainId = 1337


# 0.1 ETH
@ethAmount = 10000000000000000

##############
### Send Deposit Tx
POST {{aliceUrl}}/send-deposit-tx
Content-Type: application/json

{
  "channelAddress": "{{aliceBobChannel}}",
  "amount": "{{ethAmount}}",
  "assetId": "0x0000000000000000000000000000000000000000",
  "chainId": "{{chainId}}",
  "publicIdentifier": "{{alicePublicIdentifier}}",
}

##############
### Reconcile Deposit
POST {{bobUrl}}/deposit
Content-Type: application/json

{
  "channelAddress": "{{aliceBobChannel}}",
  "assetId": "0x0000000000000000000000000000000000000000",
  "publicIdentifier": "{{bobPublicIdentifier}}",
}

##############
### Request Collateral
POST {{daveUrl}}/request-collateral
Content-Type: application/json

{
  "channelAddress": "{{daveRogerChannel}}",
  "assetId": "0x0000000000000000000000000000000000000000",
  "publicIdentifier": "{{davePublicIdentifier}}"
}