/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LinkedTransferBodySchema {
  channelId: string;
  amount: string;
  assetId: string;
  recipient?: string;
  routingId: string;
  preImage: string;
  recipientChainId?: string;
  recipientAssetId?: string;
  meta?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
