site_name: Connext Documentation

repo_name: connext/vector
repo_url: https://github.com/connext/vector

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.png

  font:
    text: Proxima Nova
  palette:
    primary: "#002868"
    accent: "#FCA311"

  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - toc:
      toc_depth: 3
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/connext
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ConnextNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/connext
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FTxQc8C

nav:
  - Intro:
      - index.md
  - Quick Start:
      - quickStart/serverNode.md
      - quickStart/browserNode.md
  - Node Guides:
      - node/basics.md
      - node/configure.md
      # - node/depositAndWithdraw.md
      - node/transfers.md
      - node/events.md
  - Router Guides:
      - router/basics.md
      - router/configure.md
      # - router/managingCollateral.md
  - API Reference:
      - reference/nodeAPI.md
  - Changelog:
      - changelog.md